### ISSUE TITLE
compatibility between import functions

### ISSUE THREAD

**Issue by chadestep** [surmeierlab/neurphys#1]
We need to make sure the import functions from the 2P rigs and the physiology rigs is somewhat standardized. 

@DGalt: change z-fill of sweep #
@chadestep: change first column name to 'Primary'

Should be good to go after that.

**Comment by chadestep** [comment]
@DGalt 
I fixed this on my end. As soon as you fix yours and merge the branches feel free to close this issue.

**Comment by chadestep** [comment]
Actually, before you merge, what do you think of the idea of changing your import function name from 'pv_import' to 'read_pv?' I was just thinking about keeping it consistent with the current Pandas naming scheme.

**Comment by DGalt** [comment]
That's fine, I'll make that change. Are we capitalizing column names (channel names) or making them lowercase (right you your "time" column is lowercase)

**Comment by chadestep** [comment]
@DGalt This fully fixed on your end?

**Comment by DGalt** [comment]
It's fixed in the pv_import module (although I still haven't changed that to read_pv), but I still need to go through and edit all the times "Primary" and "Time" are used in the analysis modules. I will do that today.

**Comment by chadestep** [comment]
No biggie, just close the issue whenever you get around to it.

**Comment by DGalt** [comment]
Closed with ffb7f10dbd65df10a95f1f7f92f41c3ad12a916e
