### ISSUE TITLE
Future proofing

### ISSUE THREAD

**Issue by chadestep** [surmeierlab/neurphys#16]
At some point, there will be a decent overhaul of Pandas (https://wesm.github.io/pandas2-design/index.html). 

We should prevent the problems we can by keeping track of anticipated API changes and depreciated functions/methods and fix them before it becomes a problem.

And honestly, it couldn't hurt to go through the code base and do some clean up while the library is still young. Just a thought.

**Comment by DGalt** [comment]
Need to go through and remove ix from everything...

**Comment by chadestep** [comment]
This is going to involve some serious testing on our part. 

Fun times ahead.

**Comment by chadestep** [comment]
Closing this and moving it to the "Projects" tab since that's a better fit.
