### ISSUE TITLE
naming conventions and not being able to access submodules

### ISSUE THREAD

**Issue by DGalt** [surmeierlab/neurphys#23]
I'm not sure when this was changed, but when just doing `import neurphys` you have access to a number of the functions in the submodules. the problem is that a number of these functions have the same name as the submodules. 

for example, if you go `from neurphys import nuplot` you're getting the function `nuplot` from the `nuplot` module, which is not what I was expecting. Rather I was hoping to import the `nuplot` module, from which i'd then be able to call functions such as `nuplot` or `nu_genheatmap`

same thing with `read_abf`. 

normally what I do is import just the specific submodules that I need and will the call the functions associated with those modules (e.g. `import neurphys.read_pv as rpv` and then use `rpv.import_folder`)

If we're going to have, upon importing neurphys, it import a number of the functions contained in the submodules then we need to make sure that they're not named the same thing so that if someone wants to just import a particular module without importing everything else they can still do that

**Comment by chadestep** [comment]
This was set up when titipat made our initial __init__.py

I haven't thought about it in a long time, but yeah, we should go ahead and change it. Who wants the job?

**Comment by DGalt** [comment]
what do we want the solution to be? personally i don't see any reason to be importing everything in `init.py`, but that's my own preference. i'd rather have to explicitly import the submodules and then use the functions from there.

**Comment by chadestep** [comment]
It made sense when we had like, 5 functions, but yeah, it's only going to add to the technical debt of keeping the package current. I'm for explicitly importing the submodules. I can do it, but not until after the holidays.

**Comment by DGalt** [comment]
just removing everything from `init.py` is a short term solution. i'm not sure how to clean up the private functions from the submodules for tab completion though.

**Comment by chadestep** [comment]
I was just going to look how other packages did it :)

**Comment by chadestep** [comment]
Closing this for now. 

There are still quirks to work out, but it's up to par with pandas and numpy, so I think that's good enough.
